okd-project/okd

FAQ.md, README.md
Hi,
I collected a few faqs for people interested in development. I'm always searching for certain commands. I'm sure there is much more which will follow.
Greetings,
Josef
=> Add a few faqs for development.

Guides/IPI/azure/README.md
Hi,
this PR adds a few installation instructions for Azure IPI of OKD 4. As described in the guide it's not necessary anymore if FCOS has landed in the Azure Marketplace.
Greetings,
Josef
=> Add installation instructions for Azure IPI.

README.md
Prefer github releases and update steps to verify tools signature
Fixes #181
=> readme: update Getting Started section with steps to verify tools signature

README.md
Use GA build as an example in README
=> readme: update image to GA

FAQ.md
Update FAQ:
* Add Table Of Contents for easier navigation
* OKD-OCP relations
* Update improvements
* Troubleshooting
Fixes #26 
Fixes #45
=> FAQ: add more frequently asked questions

KNOWN_ISSUES.md
This file would help us and community with tracking active significant issues.
cc @dmueller2001 @LorbusChris
=> Add known issues list

FAQ.md
I've arranged the questions into categories for easier referencing, added some introductory text, and added a question/answer.
=> Style and Content Modifications to the FAQ

Guides/UPI/baremetal/nodes-custom-ip.md, Guides/UPI/baremetal/nodes-firewalls.md, Guides/UPI/baremetal/nodes-with-dual-interfaces.md
Hi, this is just a continuation of my previous PR #498 with guides for OKD deployments on bare metals as the last one got merged and I still had guides to write!
Apologies that it's taking me a while to sit down and write all of these, lots of time pressures at the moment!
Feedback and suggestions welcome :)
=> Baremetal new guides (continued)

CONTRIBUTING.md, FAQ.md, Guides/UPI/okd4-terraform-openstack/scripts/update-installer-and-image.sh, Guides/UPI/vSphere_terraform/README.md
Use `registry.ci.openshift.org` instead
=> registry.svc.ci is deprecated

README.md
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>
=> No need for the Docker adjective

README.md
It's worth pointing out for folks doing testing.
=> Added language about pruning of the nightlies

KNOWN_ISSUES.md
Update KNOWN_ISSUES.md with a list of existing common issues as of May 10.
Fixes #624
=> Update known issue list

KNOWN_ISSUES.md
Mark mirror bug as fixed, update on signature bug and fix formatting
=> known issues: reformat, update the list

FAQ.md, Guides/IPI/azure/README.md, Guides/UPI/okd4-terraform-openstack/README.md, Guides/UPI/vSphere_terraform/README.md, README.md
Follow-up for https://github.com/openshift/okd/pull/672
=> Update FAQ, README and guides with new RC url

KNOWN_ISSUES.md
Systemd-resolved is not configured properly during install
=> Systemd-resolved is not configured properly during install

KNOWN_ISSUES.md
=> Fcos 34 systemd resolved issue

KNOWN_ISSUES.md
* remove some issues resolved in latest 4.7 stable
* add mirroring issue in first OKD 4.8 release
=> Update KNOWN ISSUES

Guides/UPI/vSphere_terraform/README.md
This PR updates the timeouts for websocket connections to the Kubernetes API.
=> Update Timeout in HAProxy

KNOWN_ISSUES.md
Fix a typo in the OKD release notes
=> Fixed Effected version typo

FAQ.md
Add tips about unavailable upgrades
=> FAQ.md: update upgrade section

FAQ.md
Since we have an #okd-dev channel on kubernetes slack we should send people to it
=> Point users to the #okd-dev channel

COMMUNITY-TESTING.md
Per discussion on the Community Development meeting, here is an initial pass at a pre-release testing info document. Feedback very much welcome.
=> Community testing
