- Documentation/UPI/vSphere/vSphere.md
- README.md
Replaced the outdated 4.3 preview link with instructions on downloading 4.4 tools. Created an vSphere installation guide loosely following (and borrowing the end from) the libvirt page.
> Add instructions for UPI vSphere installation (4.4)

- README.md
The newly-linked repo claims that meeting details will be announced on okd-wg@google e-mail list, but in reality no e-mail messages are sent.
> make it easier to find OKD-WG meetings

- README.md
The README had a link to a specific version, which as of today is unavailable:
```
> oc adm release extract --tools registry.svc.ci.openshift.org/origin/release:4.4.0-0.okd-2020-01-20-084618
> error: image does not exist
```
It is better to use the 4.4 wildcard url `registry.svc.ci.openshift.org/origin/release:4.4` instead. Unless there is some specific reason to use a certain image I guess.
> Updates oc adm release image url to wildcard

- Documentation/UPI/Requirements/DNS_Bind.md
- Documentation/UPI/Requirements/LB_HAProxy.md
- Documentation/UPI/libvirt/libvirt.md
- Documentation/UPI/vSphere_terraform/README.md
- README.md
Found some spelling mistakes when reading through the docs in my editor. Also fixed the trailing spaces of the install config in the libvirt docs.
> Fix some typos and whitespaces

- .github/ISSUE_TEMPLATE/bug_report.md
* Mention that OKD 3.11 issues should be filed in openshift-ansible/origin repos
* Add a link to gather log bundle / must-gather
/cc @LorbusChris
> .github/ISSUE_TEMPLATE/bug_report: update bug report template

- README.md
OKD4 is now GA and there were a couple of remaining references to "Beta" in the README.
> readme: remove references to 'beta'

- FAQ.md
- KNOWN_ISSUES.md
- README.md
Updates to the FAQ, Known Issues, README.
> Various documentation updates and fixes

- Guides/UPI/baremetal/README.md
- Guides/UPI/baremetal/enable-disable-network-interfaces.md
- Guides/UPI/baremetal/installer-workspace.md
- Guides/UPI/baremetal/manual-dns-and-fcos-dns-fix.md
- Guides/UPI/baremetal/node-hostname-resolution.md
This is a WIP PR for adding more information on how to deploy OKD onto bare metal.
These are mainly lessons learnt "the hard way" from deploying OKD into the bare metal environment.
Guides and methods followed may not be best practise so am sharing early as I'm still writing the documents in case something is well off the mark of what should be done!
These are the guide I'm planning to author:
Document | Overview
-------- | --------
Installer Workspace | When doing bare metal deploys you may be doing a lot of them whilst having to tweak config files, manifests and more. This document contains a few tips and tricks on workspace layout.
Manual DNS Configuration and Fix Fedora CoreOS (FCOS) resolv bug | FCOS 33 contains a bug which breaks DNS during a fresh bare metal deploy. This document …
> Add some more Bare Metal guides

- README.md
When following this README, I was quite confused when oc extracts the same tarballs again. It turns out the `oc adm` command is an alternative way to obtain the openshift installer and client.
> Clarify the installation of `oc` and `openshift-install`

- Guides/UPI/vSphere_terraform/machine/main.tf
- Guides/UPI/vSphere_terraform/main.tf
60GByte is too small after a few upgrades to the cluster have been applied.
> vSphere UPI: Make disk_size of VMs customizable and increase it to 128GByte.

- FAQ.md
This section is causing some confusion about support terms and ToS. OKD community would soon have a special catalog with Red Hat operators as a replacement.
> FAQ: remove non-community catalog tip

- Guides/UPI/okd4-terraform-openstack/install-config.yaml
- Guides/UPI/vSphere_terraform/README.md
- README.md
Due to various problems, we should change our fake pull secret example to a fake secret that is parsable.
Related issues:
- #264
- #576
Note: At the moment I have not tested an okd installation with this pull-secret, but I will do so this week.
> Change fake pull secret to a parsable value

- FAQ.md
The following workaround was very helpful to solve the missing libvirt libraries under Ubuntu.
> Add FAQ/misc: How to use the official installation container with docker/podman

- KNOWN_ISSUES.md
origin-release.svc.ci.openshift.org was taken down before we could include a change for this in stable releases.
This commit describes the issue and adds a workaround
> Add CannotRetrieveUpdates alert known issue

- KNOWN_ISSUES.md
Add a note that its resolved in 4.7.0-0.okd-2021-06-13-090745
> KNOWN_ISSUE: update "Provision node fails with fcos image 33.20210301.3.1 and later"

- troubleshooting/log-bundle.md
This adds a new `troubleshooting` directory with technical details about debugging components.
First guide is related to log-bundles we use to debug failed installations.
> Add a short guide how to read log-bundles

- KNOWN_ISSUES.md
Add note about known issue with systemd crashing in 2021-08-07 because of upstream.
> Update KNOWN_ISSUES for systemd-248.5-1.fc34.x86_64 crash in 4.7.0-0.okd-2021-08-07-063045

- KNOWN_ISSUES.md
Add a note that systemd has been updated in 4.7.0-0.okd-2021-08-22-163618
cc @ptudor
> KNOWN_ISSUES: add a note about systemd crashing fix

- FAQ.md
- KNOWN_ISSUES.md
Various tests have shown this is not possible with versions >4.5 using just the installer. It consistently fails with less than three control nodes.
> Updated FAQ to accurately reflect status of single-node cluster installations

- FAQ.md
The OpenShift installer binary is called openshift-install, not openshift-installer.
> Fix a tool name typo in FAQ

- KNOWN_ISSUES.md
See https://github.com/openshift/okd/issues/1160
> KNOWN_ISSUES: add CephFS bug

- README.md
keys.html was removed after okd.io migrated to a new platform,
README should link to the public key directly
Fixes #1319
> README.md: fix public key location

- Guides/UPI/baremetal/node-hostname-resolution.md
As it was referring to workers instead of masters - copying it didn't set up the hostname-fixing service on master nodes as desired.
> Fixed master hostname YAML template
